### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by maoyali** [ortegatron/liveposetracker#1]
I think It's a good idea for me, but I don't know how to run your code, can you give the instructions in the readme.txt. Thanks!

**Comment by ortegatron** [comment]
Hi, I've just updated the readme.
It's just to do
cd src
python Twister.py
IF everything is set up properly it will start to show the captured video from webcam with the tracker detections

**Comment by xiaobaozi1996** [comment]
Thanks~
